### ISSUE TITLE
[feat] 반려동물 프로필

### ISSUE THREAD

**Issue by choijinsung05** [TeamYongChoi/RecordPet#2]
## 🚀 추가사항 
- 반려동물 프로필 조회 기능
- 반려동물 프로필 등록 기능
- 반려동물 프로필 수정 기능
- 반려동물 프로필 삭제 기능

**기능 설명**:  
- 반려동물의 프로필을 관리할 수 있도록 CRUD 기능 구현
- 사용자가 반려동물의 정보를 체계적으로 관리할수 있다.

---

## 🎯 목적 및 기대 효과  

1. **사용자 경험**: 반려동물의 정보를 관리 업데이트 할 수 있도록 지원  

---

## 🖥️ 적용 사례  
1. 사용자는 반려동물 정보를 입력하여 프로필을 등록할 수 있다.
2. 기존의 등록된 반려동물의 프로필 나이와 사진을 수정할 수 있다

---

## Task List
- [x] 프로필 등록 기능
- [x] 프로필 수정 기능
- [ ] 사진 업로드, 삭제, 수정
- [ ] 사진 resizeing
- [ ] 기본 프로필 이미지 대체 로직 추가
- [ ] 테스트 코드 작성

## 📎 추가 정보  
기능 구현과 관련된 참고 자료나 스크린샷이 있다면 첨부해주세요.
